// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {normalization} from '../models';
import {config} from '../models';

export function AnalyzeText(arg1:string):Promise<Array<normalization.Detection>>;

export function FixClipboard():Promise<Record<string, any>>;

export function GetConfig():Promise<config.Config>;

export function GetEngineState():Promise<Record<string, any>>;

export function Quit():Promise<void>;

export function RepairText(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ShowSettings():Promise<void>;

export function ToggleEngine():Promise<boolean>;
