// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeText(arg1) {
  return window['go']['ipc']['App']['AnalyzeText'](arg1);
}

export function FixClipboard() {
  return window['go']['ipc']['App']['FixClipboard']();
}

export function GetConfig() {
  return window['go']['ipc']['App']['GetConfig']();
}

export function GetEngineState() {
  return window['go']['ipc']['App']['GetEngineState']();
}

export function Quit() {
  return window['go']['ipc']['App']['Quit']();
}

export function RepairText(arg1) {
  return window['go']['ipc']['App']['RepairText'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['ipc']['App']['SaveConfig'](arg1);
}

export function ShowSettings() {
  return window['go']['ipc']['App']['ShowSettings']();
}

export function ToggleEngine() {
  return window['go']['ipc']['App']['ToggleEngine']();
}
